# Generated by Django 4.1.7 on 2023-02-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='Curso',
            new_name='curso',
        ),
    ]
